### ISSUE TITLE
Make a list of each test suite's default tests and extra tests in README

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-snap-testing#128]
A list can help us quickly go through which tests are disabled by default. 

For example, in edgexfoundry suite, the refresh test is disabled for a local build snap by default. When [a PR is related to upgrading](https://github.com/edgexfoundry/edgex-go/pull/4210#pullrequestreview-1153535786), we need to upload that local build snap to snapstore first, and then manually run the refresh test locally.

**Comment by farshidtz** [comment]
Describing each test suite and what it does is good, but maintaining the configuration documentation will be hard. Instead, I think we should modularize tests so we don't have to remember or document conditional testing workflows.

See also:
- #131
- #117
