### ISSUE TITLE
Rename `DisableConfigProviderXXX` function for clarity

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-snap-testing#180]
Suggestion for future work: the newly added functions `DisableConfigProviderXXX` don't actually disable the config provider. They just configure services to not use it and also to load common config from a file. For clarity, I'd call the action disuse rather than disable.

_Originally posted by @farshidtz in https://github.com/canonical/edgex-snap-testing/issues/175#issuecomment-1490134216_

**Comment by MonicaisHer** [comment]
How about `DontUseConfigProvider()`? As disuse is not commonly used in English and it also refers to the state of something no longer being used.

**Comment by farshidtz** [comment]
`DoNotUseConfigProvider()` sounds good.
