### ISSUE TITLE
Add test for checking startup status of oneshot services

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-snap-testing#193]
Oneshot services:
- security-bootstrapper-redis (oneshot service to setup secure Redis)
- security-consul-bootstrapper (oneshot service to setup secure Consul)
- security-proxy-setup (oneshot service to setup API gateway)
- security-secretstore-setup (oneshot service to setup Vault)

**Comment by farshidtz** [comment]
This is no longer needed since the services are disabled by default now: https://github.com/edgexfoundry/edgex-go/pull/4552
