### ISSUE TITLE
Add secret config test to add API gateway user

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-snap-testing#194]
Call version 3 of API on behalf of example user

**Comment by farshidtz** [comment]
The steps to be tested can be derived from the documentation: https://docs.edgexfoundry.org/3.0/getting-started/Ch-GettingStartedSnapUsers/#adding-api-gateway-users

The user creation and JWT request are already performed in:
https://github.com/canonical/edgex-snap-testing/blob/b08bb4d540470870707e2b4e0dd6316719fade34/test/utils/readings.go#L13-L20
Which better be moved to a new file named e.g. `login.go`.

A new test under the edgexfoundry suite can be to perform the login and use the JWT to call an API.

See also: https://github.com/canonical/edgex-snap-testing/issues/174
