### ISSUE TITLE
Upgrade download-artifact action to replace deprecated Node.js

### ISSUE THREAD

**Issue by farshidtz** [canonical/edgex-snap-testing#197]
Warning in tests:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/download-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by MonicaisHer** [comment]
According to the GitHub Actions documentation mentioned above, "For Actions users: Update your workflows with the latest versions of the actions that run on Node 16." This means that the version needs to be upgraded to v3:
https://github.com/canonical/edgex-snap-testing/blob/4576fe858bea825fda56ea98a334700bbd7a35a9/test/action.yml#L48
