### ISSUE TITLE
Handle the max retries error that was left uncaught in the config provider test

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-snap-testing#206]
please refer to https://github.com/canonical/edgex-config-provider/pull/15#issuecomment-1547329832

**Comment by farshidtz** [comment]
The function does not raise an error, instead it returns false on error which should be checked by the caller:
https://github.com/canonical/edgex-snap-testing/blob/4576fe858bea825fda56ea98a334700bbd7a35a9/test/utils/config.go#L221-L239

If all other tests look for a `false` value from this, we can refactor to raise an error internally.
