### ISSUE TITLE
Remove manual enable `app-options` once device-virtual's configure hook is available

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-snap-testing#65]
https://github.com/canonical/edgex-snap-testing/blob/fcd02aefccc3df92ee26440170f79584ae331d55/test/suites/ekuiper/main_test.go#L64

Remove this line once device-virtual's configure hook with [enabling `app-options` by default](https://github.com/edgexfoundry/device-virtual-go/pull/287/commits/8760134d8f81b98d9e42670833e31fee59ce4831) is available in the latest/edge channel.

**Comment by farshidtz** [comment]
The required addition is already available on latest/edge.
