### ISSUE TITLE
Platform test setting the port of all services to the same value

### ISSUE THREAD

**Issue by farshidtz** [canonical/edgex-snap-testing#78]
https://github.com/canonical/edgex-snap-testing/blob/d61a56465cb65a39e2f711f805e865b27643ed82/test/suites/edgexfoundry/main_test.go#L72-L73

These should be set to false or removed in favor of another custom test that doesn't mess with a port globally.

**Comment by MonicaisHer** [comment]
edgexfoundry's global and mixed config options could still be tested by changing `service-startupmsg` or `writable-loglevel` instead.

**Comment by farshidtz** [comment]
I suggest setting `service-startupmsg` because not all services write debug logs. Setting a value such as `snap-testing` can be easily checked in output logs.

We may need to "wait" for the message to appear, by querying the logs periodically, or following them and exiting once the message is there (with a timeout).
