### ISSUE TITLE
Manual edgex-secretstore-token connection should happen after platform installation

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-snap-testing#96]
Currently, platform snap installation happens after local snap installation and edgex-secret-token connection, and it will cause an error. Here is an example:

```
[exec] sudo snap install --dangerous app-rfid-llrp-inventory/edgex-app-rfid-llrp-inventory_2.1.0-dev.3_amd64.snap
[stdout] edgex-app-rfid-llrp-inventory 2.1.0-dev.3 installed
[exec] sudo snap connect edgexfoundry:edgex-secretstore-token edgex-app-rfid-llrp-inventory:edgex-secretstore-token
stderr] error: snap "edgexfoundry" is not installed
exit status 1
```

This need to be fixed in all test suites. Maybe remove following line before local snap installation:
https://github.com/canonical/edgex-snap-testing/blob/b0763c032bc3d14b0e966939c1a1a6f1c33beb3a/test/suites/app-service-configurable/main_test.go#L45

**Comment by farshidtz** [comment]
The following PRs fail their workflow runs because of this bug:
- https://github.com/edgexfoundry/device-virtual-go/pull/297
- https://github.com/edgexfoundry/device-rest-go/pull/208
- https://github.com/edgexfoundry/device-rfid-llrp-go/pull/103
- https://github.com/edgexfoundry/device-gpio/pull/50
